{"uid":"17f20ea59c2f4663","name":"test_reject_negative_max_size_value_returns_400","fullName":"test.teams.test_get_users_team#test_reject_negative_max_size_value_returns_400","historyId":"8d6372b5391c65dd7484be55d14f7411","time":{"start":1725939964064,"stop":1725939964411,"duration":347},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 400, but got 500. Response text:","statusTrace":"setup_teardown_user_team = {'createdAt': '2024-09-10 03:46:00', 'deleted': False, 'id': '66dfc0f86c86c8b7d', 'layoutSetId': '66d8f8ff4f1c23bca', ...}\n\n    @pytest.mark.listuserteam\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_reject_negative_max_size_value_returns_400(setup_teardown_user_team):\n        team = setup_teardown_user_team\n        url = EndpointTeams.get_list_users_team(team['id'], maxSize=-1)\n        response = TeamService.get_list_users_team(url)\n>       AssertionManager.assert_status_code_400(response)\n\ntest/teams/test_get_users_team.py:100: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    @staticmethod\n    def assert_status_code_400(response):\n        logger.info(f\"Validating status code 400 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 400, (\n                f\"Expected status code 400, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 400, but got 500. Response text:\n\ncore/assertions/status_code_assertion.py:37: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1725939934214,"stop":1725939934231,"duration":17},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_teardown_user_team","time":{"start":1725939960069,"stop":1725939960862,"duration":793},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 400, but got 500. Response text:","statusTrace":"setup_teardown_user_team = {'createdAt': '2024-09-10 03:46:00', 'deleted': False, 'id': '66dfc0f86c86c8b7d', 'layoutSetId': '66d8f8ff4f1c23bca', ...}\n\n    @pytest.mark.listuserteam\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_reject_negative_max_size_value_returns_400(setup_teardown_user_team):\n        team = setup_teardown_user_team\n        url = EndpointTeams.get_list_users_team(team['id'], maxSize=-1)\n        response = TeamService.get_list_users_team(url)\n>       AssertionManager.assert_status_code_400(response)\n\ntest/teams/test_get_users_team.py:100: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    @staticmethod\n    def assert_status_code_400(response):\n        logger.info(f\"Validating status code 400 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 400, (\n                f\"Expected status code 400, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 400, but got 500. Response text:\n\ncore/assertions/status_code_assertion.py:37: AssertionError","steps":[],"attachments":[{"uid":"5ae6fffd13ad3b90","name":"log","source":"5ae6fffd13ad3b90.txt","type":"text/plain","size":1857},{"uid":"e69b1d8832dfc944","name":"stderr","source":"e69b1d8832dfc944.txt","type":"text/plain","size":1926}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true},"afterStages":[{"name":"setup_teardown_user_team::0","time":{"start":1725939966884,"stop":1725939967248,"duration":364},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"listuserteam"},{"name":"parentSuite","value":"test.teams"},{"name":"suite","value":"test_get_users_team"},{"name":"host","value":"fv-az1272-901"},{"name":"thread","value":"2128-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.teams.test_get_users_team"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)","listuserteam"]},"source":"17f20ea59c2f4663.json","parameterValues":[]}