{"uid":"4ddcd052a2003387","name":"test_reject_negative_offset_value_returns_400","fullName":"test.teams.test_get_users_team#test_reject_negative_offset_value_returns_400","historyId":"774b76eee1a90d302465e571d60236dc","time":{"start":1726088735830,"stop":1726088736032,"duration":202},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 400, but got 500. Response text:","statusTrace":"setup_teardown_user_team = {'createdAt': '2024-09-11 21:05:34', 'deleted': False, 'id': '66e2061e2aa9c10d3', 'layoutSetId': '66d8f8ff4f1c23bca', ...}\n\n    @pytest.mark.listuserteam\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_reject_negative_offset_value_returns_400(setup_teardown_user_team):\n        team = setup_teardown_user_team\n        url = EndpointTeams.get_list_users_team(team['id'], offset=-1)\n        response = TeamService.get_list_users_team(url)\n>       AssertionManager.assert_status_code_400(response)\n\ntest/teams/test_get_users_team.py:91: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    @staticmethod\n    def assert_status_code_400(response):\n        logger.info(f\"Validating status code 400 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 400, (\n                f\"Expected status code 400, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 400, but got 500. Response text:\n\ncore/assertions/status_code_assertion.py:37: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1726088720920,"stop":1726088720938,"duration":18},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_teardown_user_team","time":{"start":1726088733998,"stop":1726088734371,"duration":373},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 400, but got 500. Response text:","statusTrace":"setup_teardown_user_team = {'createdAt': '2024-09-11 21:05:34', 'deleted': False, 'id': '66e2061e2aa9c10d3', 'layoutSetId': '66d8f8ff4f1c23bca', ...}\n\n    @pytest.mark.listuserteam\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_reject_negative_offset_value_returns_400(setup_teardown_user_team):\n        team = setup_teardown_user_team\n        url = EndpointTeams.get_list_users_team(team['id'], offset=-1)\n        response = TeamService.get_list_users_team(url)\n>       AssertionManager.assert_status_code_400(response)\n\ntest/teams/test_get_users_team.py:91: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    @staticmethod\n    def assert_status_code_400(response):\n        logger.info(f\"Validating status code 400 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 400, (\n                f\"Expected status code 400, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 400, but got 500. Response text:\n\ncore/assertions/status_code_assertion.py:37: AssertionError","steps":[],"attachments":[{"uid":"7b76ae4df164e475","name":"log","source":"7b76ae4df164e475.txt","type":"text/plain","size":1857},{"uid":"4f4b609622f1f64e","name":"stderr","source":"4f4b609622f1f64e.txt","type":"text/plain","size":1926}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true},"afterStages":[{"name":"setup_teardown_user_team::0","time":{"start":1726088737414,"stop":1726088737581,"duration":167},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"listuserteam"},{"name":"parentSuite","value":"test.teams"},{"name":"suite","value":"test_get_users_team"},{"name":"host","value":"fv-az1532-294"},{"name":"thread","value":"2075-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.teams.test_get_users_team"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)","listuserteam"]},"source":"4ddcd052a2003387.json","parameterValues":[]}