{"uid":"c74ec9ee9d0fd851","name":"test_negative_max_size_returns_400","fullName":"test.users.test_get_users#test_negative_max_size_returns_400","historyId":"442c759c1f94256f089458b272e417c0","time":{"start":1728316990629,"stop":1728316991016,"duration":387},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 400, but got 500. Response text:","statusTrace":"setup_teardown_user = {'accountsIds': [], 'accountsNames': {}, 'authMethod': None, 'avatarColor': '#ef2b2b', ...}\n\n    @pytest.mark.listuser\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_negative_max_size_returns_400(setup_teardown_user):\n        url = EndpointUser.get_list_user(maxSize=-1)\n        response = UserService.get_list_user(url)\n>       AssertionManager.assert_status_code_400(response)\n\ntest/users/test_get_users.py:59: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    @staticmethod\n    def assert_status_code_400(response):\n        logger.info(f\"Validating status code 400 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 400, (\n                f\"Expected status code 400, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 400, but got 500. Response text:\n\ncore/assertions/status_code_assertion.py:37: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1728316911923,"stop":1728316911940,"duration":17},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_teardown_team_global","time":{"start":1728316979929,"stop":1728316980315,"duration":386},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_teardown_user","time":{"start":1728316988743,"stop":1728316989133,"duration":390},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 400, but got 500. Response text:","statusTrace":"setup_teardown_user = {'accountsIds': [], 'accountsNames': {}, 'authMethod': None, 'avatarColor': '#ef2b2b', ...}\n\n    @pytest.mark.listuser\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_negative_max_size_returns_400(setup_teardown_user):\n        url = EndpointUser.get_list_user(maxSize=-1)\n        response = UserService.get_list_user(url)\n>       AssertionManager.assert_status_code_400(response)\n\ntest/users/test_get_users.py:59: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    @staticmethod\n    def assert_status_code_400(response):\n        logger.info(f\"Validating status code 400 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 400, (\n                f\"Expected status code 400, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 400, but got 500. Response text:\n\ncore/assertions/status_code_assertion.py:37: AssertionError","steps":[],"attachments":[{"uid":"6a1d238f7882bd65","name":"log","source":"6a1d238f7882bd65.txt","type":"text/plain","size":1971},{"uid":"bc750fd784fadf98","name":"stderr","source":"bc750fd784fadf98.txt","type":"text/plain","size":2040}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true},"afterStages":[{"name":"setup_teardown_user::0","time":{"start":1728316992132,"stop":1728316992552,"duration":420},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_teardown_team_global::0","time":{"start":1728317015225,"stop":1728317015585,"duration":360},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"listuser"},{"name":"parentSuite","value":"test.users"},{"name":"suite","value":"test_get_users"},{"name":"host","value":"fv-az1567-222"},{"name":"thread","value":"2096-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.users.test_get_users"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)","listuser"]},"source":"c74ec9ee9d0fd851.json","parameterValues":[]}